global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: prom

rule_files:
  - /etc/prometheus/alerts/*.rules

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'cadvisor-private'
    static_configs:
      - targets:
          - 'cadvisor:8080'
    metric_relabel_configs:
      - action: labeldrop
        regex: 'container_label_.+'
      - action: labeldrop
        regex: 'image'

  - job_name: 'node-exporter-private'
    static_configs:
      - targets:
          - 'node-exporter:9100'

#  - job_name: 'cadvisor-public'
#    scheme: 'https'
#    basic_auth:
#      username: 'DevOps'
#      password: '<secret>'
#    tls_config:
#      server_name: 'pod1.monitor.byparsa.dev'
#      insecure_skip_verify: false
#    static_configs:
#      - targets:
#          - 'pod1.monitor.byparsa.dev:443'
#    sample_limit: 10000
#    metric_relabel_configs:
#      - action: labeldrop
#        regex: 'container_label_.+'
#      - action: labeldrop
#        regex: 'image'

#  - job_name: 'node-exporter-public'
#    scheme: 'https'
#    basic_auth:
#      username: 'DevOps'
#      password: '<secret>'
#    tls_config:
#      server_name: 'node1.monitor.byparsa.dev'
#      insecure_skip_verify: false
#    static_configs:
#      - targets:
#          - 'node1.monitor.byparsa.dev:443'
#    sample_limit: 10000

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets:
          - 'blackbox-exporter:9115'

  - job_name: 'blackbox-ping'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module:
        - icmp_ipv4
    static_configs:
      - targets:
          - 8.8.8.8
          - google.com
          - node-exporter
          - blackbox-exporter
          - cadvisor
          - pushgateway
          - alertmanager
          - grafana
          - prometheus
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'grafana'
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'grafana:3000'

  - job_name: 'alertmanager'
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'alertmanager:9093'

  - job_name: 'pushgateway'
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'pushgateway:9091'

  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'traefik:8082'